### ISSUE TITLE
v5 could export default trimNewlines

### ISSUE THREAD

**Issue by nealeu** [sindresorhus/trim-newlines#13]
v5 causes an unnecessary breakage where you could still provide a default export of trimNewlines so that people don't get things like:

```
✖ stylelint scss:
file:///home/neale/dev/solum/solum-xplain-ui/node_modules/stylelint/node_modules/meow/index.js:9
import trimNewlines from 'trim-newlines';
       ^^^^^^^^^^^^
SyntaxError: The requested module 'trim-newlines' does not provide an export named 'default'
```

**Comment by sindresorhus** [comment]
It doesn't make sense to provide both default and named export of the same thing. The change was done in a major release.

**Comment by nealeu** [comment]
Of course. Not sure why I didn't investigate why on earth npm 9.6.7 is providing v5 when meow has:
```
    "trim-newlines": "^4.0.2",
```
[edit]  Because some other dev put an override in to v5! Sorry
