### ISSUE TITLE
There is no source tag for 3.0.1

### ISSUE THREAD

**Issue by aredridel** [sindresorhus/trim-newlines#4]
It should be commit b10d5f4afef832b16bc56d49fc52c68cbd403869 according to npm metadata, but that's not in the repo currently.

**Comment by sindresorhus** [comment]
Correct. It was backported. I didn't bother to tag it. The relevant branch here: https://github.com/sindresorhus/trim-newlines/tree/v3-0-1

**Comment by aredridel** [comment]
Ah, cool. Just made exploring it from the dependabot updates a task to download source and compare.
