### ISSUE TITLE
Add support for both CJS and ESM

### ISSUE THREAD

**Issue by kedrzu** [sindresorhus/trim-newlines#9]
Using this package in Node JS with any other packages written in CJS is hardly possible.
Would be cool to have both formats in one package.

It's as easy as adding to `package.json`:
```
"exports": {
    ".": {
      "require": "./index.cjs", // CJS
      "import": "./index.mjs"   // ESM
    }
}
```
Source: https://antfu.me/posts/publish-esm-and-cjs

I see a lot of packages, that migrate to ESM without providing any backward compatibility, rendering those packages almost impossible to use in a real dev environment.

If you are not sure, that still supporting CJS is a good thing, take a look at package statistics:
![image](https://user-images.githubusercontent.com/2473784/155684240-aa2ca813-7f5b-43b0-991a-82dcdc569fd3.png)

It's 17x more downloads for CJS version than ESM one.

**Comment by sindresorhus** [comment]
No plans to support CommonJS. Hybrid packages have a lot of problems too.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
